### ISSUE TITLE
Could you please replace FetchContent_Declare(ftxui) with find_package(ftxui REQUIRED)?

### ISSUE THREAD

**Issue by yurivict** [DanArmor/turing_cmd#2]

**Comment by DanArmor** [comment]
Hello, didn't see a notification for issue - sorry for the late response 😃 

I want to have possibility of building project without pre-compiled binaries on machine, so can't just replace with `find_package`.

But i added [find_package integration for FetchContent](https://cmake.org/cmake/help/latest/guide/using-dependencies/index.html#fetchcontent-and-find-package-integration) - **first** it will try to find pre-compiled binary on machine by `find_package`, and if there is non - will use `FetchContent` to get sources and build library.

Can the issue be considered solved?

**Comment by yurivict** [comment]
Thanks.
